from pygame import Vector2

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60
TITLE = "Mars Survival Rover"

WORLD_WIDTH = 3000
WORLD_HEIGHT = 3000

BIOME_CELL_SIZE = 60
WORLD_SEED_MIN = 1
WORLD_SEED_MAX = 999999

COLOR_BG = (45, 35, 40)
COLOR_PLAYER = (200, 180, 120)
COLOR_RESOURCE = (100, 200, 255)
COLOR_BASE = (80, 200, 100)
COLOR_HUD_BG = (30, 30, 35)
COLOR_ENERGY = (255, 200, 80)
COLOR_SIGNAL = (120, 180, 255)
COLOR_TEXT = (230, 230, 230)
COLOR_STORM_OVERLAY = (120, 90, 70)

BASE_POSITION = Vector2(WORLD_WIDTH / 2, WORLD_HEIGHT / 2)
PLAYER_START_X = WORLD_WIDTH / 2.0
PLAYER_START_Y = WORLD_HEIGHT / 2.0
START_CRATER_RADIUS = 140.0

SIGNAL_MAX = 100.0

SIGNAL_DECAY_PER_PIXEL = 0.08
STORM_SIGNAL_DISTANCE_FACTOR = 1.75

SIGNAL_BASE_DRAIN = 0.30      
SIGNAL_STORM_DRAIN = 5.0       
SIGNAL_ROCKS_REGEN = 1.0       
SIGNAL_SAFE_ZONE_REGEN = 5.5   
PLAYER_SIZE = (28, 22)
PLAYER_ACCELERATION = 720.0
PLAYER_MAX_SPEED = 260.0
PLAYER_ACCEL_LERP = 14.0
PLAYER_BRAKE_FRICTION = 11.0
PLAYER_COAST_FRICTION = 4.2
INPUT_SMOOTH_SPEED = 16.0
PLAYER_TILT_MAX_DEG = 12.0
MICRO_SHAKE_ON_BURST = 2.8
MICRO_SHAKE_ON_TURN = 1.6
TURN_DOT_THRESHOLD = -0.25
PLAYER_STORM_RESISTANCE = 0.6
BOOST_COOLDOWN = 2.5
BOOST_ACCEL_MUL = 2.2
BOOST_DURATION = 0.30

PLAYER_START_ENERGY = 100.0
ENERGY_DRAIN_PER_SECOND = 0.35
ENERGY_DRAIN_MOVE_COEF = 0.0002  
ENERGY_GAIN_PER_RESOURCE = 20.0

STORM_START_CHANCE_PER_SEC = 0.055
STORM_MIN_DURATION = 7.0
STORM_MAX_DURATION = 14.0
STORM_INTENSITY_MIN = 1.0
STORM_INTENSITY_MAX = 2.4
STORM_WIND_ON_VELOCITY = 0.12
STORM_ENERGY_DRAIN = 0.1
STORM_SIGNAL_OFFSET_DRAIN = 0.2

STORM_BUILDUP_INTENSITY_FLOOR = 0.30  
STORM_FADE_INTENSITY_FLOOR    = 0.28  

PARTICLE_MAX = 300
PARTICLE_SPAWN_BASE = 46.0
PARTICLE_SPEED_MIN = 30.0
PARTICLE_SPEED_MAX = 220.0

STORM_SAFE_ZONE_COUNT_MAX = 3
STORM_SAFE_ZONE_RADIUS_MIN = 70.0
STORM_SAFE_ZONE_RADIUS_MAX = 140.0
STORM_SAFE_ZONE_LIFETIME_MIN = 6.0
STORM_SAFE_ZONE_LIFETIME_MAX = 12.0
STORM_SAFE_ZONE_WIND_MUL = 0.16         
STORM_SAFE_ZONE_DAMAGE_MUL = 0.10       
STORM_SAFE_ZONE_SIGNAL_DRAIN_MUL = 0.20  

STORM_MICRO_STORM_COUNT_MAX = 3
STORM_MICRO_STORM_RADIUS_MIN = 45.0
STORM_MICRO_STORM_RADIUS_MAX = 95.0
STORM_MICRO_STORM_LIFETIME_MIN = 2.5
STORM_MICRO_STORM_LIFETIME_MAX = 6.0
STORM_MICRO_STORM_SPAWN_COOLDOWN = 1.1
STORM_MICRO_STORM_PUSH_BASE = 170.0
STORM_MICRO_STORM_CONTROL_LOSS_TIME = 0.75
STORM_CONTROL_LOSS_EXTRA_DRAG = 18.0
STORM_MICRO_STORM_ENERGY_PENALTY = 14.0

STORM_ENERGY_BURST_COUNT_MAX = 2
STORM_ENERGY_BURST_PROB_PER_SEC = 0.075
STORM_ENERGY_BURST_RADIUS = 38.0
STORM_ENERGY_BURST_LIFETIME = 1.4
STORM_ENERGY_BURST_BONUS_BASE = 26.0
STORM_ENERGY_BURST_RISK_PENALTY_BASE = 18.0

STORM_TURBULENCE_JITTER = 160.0  
STORM_TURBULENCE_DRAG = 6.8  

STORM_FLASH_DECAY = 2.6
STORM_GUST_SOUND_PROB_PER_SEC = 0.12
STORM_GUST_SOUND_INTENSITY_MIN = 0.6
STORM_ENERGY_BURST_SOUND_VOLUME = 0.62

RESOURCE_COUNT = 22
RESOURCE_SIZE = (16, 16)
RESOURCE_POP_DURATION = 0.12   

RESOURCE_PROMPT_RANGE      = 88.0    
RESOURCE_SCAVENGE_SPEED_LIMIT = 55.0 
RESOURCE_SCAVENGE_DURATIONS = {      
    "common":   2.0,
    "damaged":  1.5,
    "unstable": 3.2,
    "corrupted": 1.8,
}
RESOURCE_ENERGY_RELAY      = 16.0  
RESOURCE_ENERGY_TECH       = 22.0   
RESOURCE_CORRUPTED_SIGNAL_DRAIN = 10.0
RESOURCE_CORRUPTED_ENERGY_DRAIN = 12.0

SIGNAL_PICKUP_COUNT = 12
REAL_SIGNAL_CHANCE = 0.65
SIGNAL_PICKUP_RADIUS = 10
SIGNAL_FLASH_DURATION = 0.22

SIGNAL_PROMPT_RANGE = 115.0       
SIGNAL_CONNECT_RANGE = 78.0        
SIGNAL_CONNECT_SPEED_LIMIT = 45.0 
SIGNAL_CONNECT_RATE = 20.0        
SIGNAL_CONNECT_BREAK_PENALTY = 5.0 
SIGNAL_CONNECT_DURATION = 4.5     

SIGNAL_FAKE_DRAIN_RATE = 10.0     
CORRUPT_REVEAL_MIN = 2.5           
CORRUPT_REVEAL_MAX = 6.0         
CORRUPT_EARLY_DURATION = 2.2      
CORRUPT_MID_DURATION = 2.0        
CORRUPT_FAKE_REGEN = 3.5       
CORRUPT_FAIL_SIGNAL_PENALTY = 18.0 
CORRUPT_CAM_JITTER_CHANCE = 0.35   
CORRUPT_CAM_JITTER_T = 1.6         

MAGNETIC_CORRUPT_SPEED_ADD = 0.55
STORM_CORRUPT_SPEED_ADD = 0.45

NOTIFICATION_BOTTOM_OFFSET = 58   
ANCIENT_SHADOW_CHANCE    = 0.50  
ANCIENT_NONSHADOW_CHANCE = 0.08  
RESOURCE_RESPAWN_PER_SEC = 0.12

WIN_RESOURCES = 5
WIN_REAL_SIGNALS = 3

SAFE_STATION_RADIUS = 390.0       
SAFE_STATION_INTERACT_RANGE = 120.0 
SAFE_STATION_NO_CORRUPT_RADIUS = 600.0  
STATION_STORM_DAMPEN = 0.06      
STATION_SIGNAL_REGEN = 4.5     
STATION_ENERGY_REGEN = 7.0     

SHAKE_BASE_AMPLITUDE = 4

CAMERA_LERP = 5.5
PARALLAX_SCROLL_MUL = 0.085
MICRO_FX_MAX = 120
HUD_LERP_SPEED = 10.0
HUD_BAR_OUTLINE = (55, 48, 52)

FADE_IN_SPEED = 2.2
FADE_OUT_SPEED = 1.8

GLITCH_SIGNAL_THRESHOLD = 0.22

ENERGY_DRAIN_BOOST_PER_SEC = 8.0
WARN_ENERGY_LOW = 30.0
WARN_SIGNAL_LOW = 35.0


UPGRADE_THRESHOLD_L1 = 3     
UPGRADE_THRESHOLD_L2 = 8     
UPGRADE_THRESHOLD_L3 = 16    
CRITICAL_UPGRADES = frozenset([
    "signal_stab", "long_range_rx", "battery_ext", "engine_upg", "storm_shield",
])

FINAL_MISSION_COUNTDOWN = 300.0  
BEACON_INTERACT_RANGE   = 140.0
CINEMATIC_DURATION      = 24.0 

SAFE_ZONE_COUNT              = 9     
SAFE_ZONE_RADIUS_MIN         = 65.0
SAFE_ZONE_RADIUS_MAX         = 115.0
SAFE_ZONE_DRAIN_REDUCTION_MIN = 0.88  
SAFE_ZONE_DRAIN_REDUCTION_MAX = 0.94  
SAFE_ZONE_MIN_DIST           = 360.0 
SAFE_ZONE_MIN_PLAYER_DIST    = 520.0  
